# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=50)),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[(b'plv', 'Pluviom\xe9trica'), (b'lnm', 'Linim\xe9trica')], max_length=4)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Esta\xe7\xe3o',
                'verbose_name_plural': 'Esta\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='EstacaoSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.Estacao')),
            ],
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('site', models.CharField(max_length=254)),
                ('url', models.CharField(max_length=254, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=50)),
                ('tipo', models.CharField(choices=[(b'niv', 'N\xedvel'), (b'vrnce', 'Variance')], max_length=5)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.AddField(
            model_name='estacaosensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.Sensor'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.Fonte'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='sensores',
            field=models.ManyToManyField(through='estacoes.EstacaoSensor', to='estacoes.Sensor'),
        ),
        migrations.AlterUniqueTogether(
            name='estacaosensor',
            unique_together=set([('estacao', 'sensor')]),
        ),
        migrations.AlterUniqueTogether(
            name='estacao',
            unique_together=set([('codigo', 'fonte')]),
        ),
    ]
