# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaLeitura', models.DateTimeField(db_index=True)),
                ('horaRecebida', models.DateTimeField(blank=True, null=True)),
                ('horaEnviada', models.DateTimeField(blank=True, null=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.Estacao')),
            ],
            options={
                'ordering': ['-horaLeitura'],
                'get_latest_by': 'horaLeitura',
            },
        ),
        migrations.CreateModel(
            name='LeituraChuva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m15', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 15 min')),
                ('m30', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 30 min')),
                ('h01', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 01 hora')),
                ('h02', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 02 horas')),
                ('h03', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 03 horas')),
                ('h04', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 04 horas')),
                ('h06', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 06 horas')),
                ('h12', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 12 horas')),
                ('h24', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'EM 24 horas')),
                ('h36', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 36 horas')),
                ('h48', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 42 horas')),
                ('h72', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 72 horas')),
                ('h96', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 96 horas')),
                ('h168', models.FloatField(blank=True, db_index=True, null=True, verbose_name=b'Em 168 horas')),
                ('mes', models.FloatField()),
                ('leitura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dados.Leitura')),
            ],
            options={
                'ordering': ('-leitura__horaLeitura',),
                'get_latest_by': 'leitura__horaLeitura',
            },
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.Leitura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacoes.Sensor')),
            ],
            options={
                'ordering': ('-leitura__horaLeitura',),
                'get_latest_by': 'leitura__horaLeitura',
            },
        ),
        migrations.AlterUniqueTogether(
            name='leiturasensor',
            unique_together=set([('leitura', 'sensor')]),
        ),
        migrations.AlterUniqueTogether(
            name='leitura',
            unique_together=set([('horaLeitura', 'estacao')]),
        ),
        migrations.AlterIndexTogether(
            name='leitura',
            index_together=set([('horaLeitura', 'estacao')]),
        ),
    ]
