# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 22:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20161027_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='tipo',
            field=models.CharField(choices=[(b'mt', b'motorway'), (b'tk', b'trunk'), (b'pm', b'primary'), (b'sc', b'secondary'), (b'tt', b'tertiary'), (b'rd', b'residential'), (b'sv', b'service'), (b'ft', b'footway'), (b'tr', b'track'), (b'pd', b'pedestrian'), (b'ph', b'path'), (b'mtl', b'motorway_link'), (b'pml', b'primary_link'), (b'ttl', b'tertiary_link'), (b'tkl', b'trunk_link'), (b'scl', b'secondary_link'), (b'ls', b'living_street'), (b'cy', b'cycleway'), (b'sp', b'steps'), (b'ri', b'rail'), (b'pi', b'pier'), (b'un', b'unclassified')], max_length=4),
        ),
    ]
