# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20161104_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logradouro',
            unique_together=set([('codigo', 'nome')]),
        ),
    ]
