# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20161104_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logradouro',
            name='nome',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
