# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20161104_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'ordering': ['altitude'],
                'verbose_name': 'Curva de N\xedvel',
                'verbose_name_plural': 'Curva de N\xedvel',
            },
        ),
    ]
