# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_curvanivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvanivel',
            name='altitude',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
