# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estacaosensor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='estacaosensor',
            name='estacao',
        ),
        migrations.RemoveField(
            model_name='estacaosensor',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='estacao',
            name='sensores',
        ),
        migrations.DeleteModel(
            name='EstacaoSensor',
        ),
    ]
