# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 15:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('altitude', models.DecimalField(
                    db_index=True, decimal_places=2, max_digits=5)),
                ('observacao', models.CharField(
                    max_length=254, null=True)),
                ('cota', models.DecimalField(
                    db_index=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['cota'],
                'verbose_name': 'Cota',
                'verbose_name_plural': 'Cotas',
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('codigo', models.IntegerField(db_index=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(
                    srid=4326)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
            },
        ),
        migrations.AlterUniqueTogether(
            name='logradouro',
            unique_together=set([('codigo', 'nome')]),
        ),
        migrations.AddField(
            model_name='cota',
            name='logradouro',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='geo.Logradouro'),
        ),
    ]
