# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cota',
            options={'ordering': ['cota'], 'verbose_name': 'Cota', 'verbose_name_plural': 'Cotas'},
        ),
        migrations.RenameField(
            model_name='cota',
            old_name='cheia',
            new_name='altitude',
        ),
        migrations.AddField(
            model_name='cota',
            name='cota',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
